server:
  port: 8082

axon:
  serializer:
    general: jackson
  axonserver:
    servers: localhost:8124
    component-name: restaurant

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/axon
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: DEBUG
